#!/bin/sh

/usr/libexec/fan-control init

if ! uci -q get 'luci-fan.@luci-fan[0]' >/dev/null 2>&1; then
	uci -q add luci-fan luci-fan >/dev/null 2>&1
fi

uci -q get 'luci-fan.@luci-fan[0].mode' >/dev/null 2>&1 || uci -q set 'luci-fan.@luci-fan[0].mode=smart'
uci -q get 'luci-fan.@luci-fan[0].manual_pwm' >/dev/null 2>&1 || uci -q set 'luci-fan.@luci-fan[0].manual_pwm=70'
uci -q get 'luci-fan.@luci-fan[0].on_temp' >/dev/null 2>&1 || uci -q set 'luci-fan.@luci-fan[0].on_temp=55'
uci -q get 'luci-fan.@luci-fan[0].off_temp' >/dev/null 2>&1 || uci -q set 'luci-fan.@luci-fan[0].off_temp=50'
uci -q get 'luci-fan.@luci-fan[0].poll_interval' >/dev/null 2>&1 || uci -q set 'luci-fan.@luci-fan[0].poll_interval=3'
uci -q commit luci-fan >/dev/null 2>&1

uci -q delete ucitrack.@luci-fan[-1]
uci -q commit ucitrack >/dev/null 2>&1

exit 0
