#!/bin/sh
uci -q delete sfp-status.settings.interface
uci -q commit sfp-status
rm -f /usr/share/luci/menu.d/luci-app-sfp-status.json
rm -f /www/luci-static/resources/view/sfp-status/overview.js
rm -f /www/luci-static/resources/sfp-status/common.js
rm -rf /var/luci-modulecache/
rm -f /var/luci-indexcache.*
[ -x /etc/init.d/rpcd ] && /etc/init.d/rpcd reload
exit 0